[package]
name = "state-machine"
version = "0.1.0"
authors = ["Phil <PhilboBaggins@users.noreply.github.com>"]
edition = "2018"
description = "Experimenting with writing a state machine in Rust"

[dependencies]
random-integer = "1.0.4"
